services:
  - type: web
    name: nodejs-express-app
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    plan: free
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: "your-redis-password"
      - key: NODE_ENV
        value: production
      - key: KAFKA_BROKER
        value: kafka:9092

  - type: redis
    name: redis
    plan: free
    envVars:
      - key: REDIS_PASSWORD
        value: "your-redis-password"

  - type: pserv
    name: zookeeper
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ZOOKEEPER_CLIENT_PORT
        value: "2181"

  - type: pserv
    name: kafka
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - key: KAFKA_LISTENERS
        value: PLAINTEXT://0.0.0.0:9092
      - key: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://kafka:9092
      - key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: PLAINTEXT:PLAINTEXT
